Traceback (most recent call last):
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\jupyter_cache\executors\utils.py", line 51, in single_nb_execution
    executenb(
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\nbclient\client.py", line 1204, in execute
    return NotebookClient(nb=nb, resources=resources, km=km, **kwargs).execute()
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\nbclient\util.py", line 84, in wrapped
    return just_run(coro(*args, **kwargs))
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\nbclient\util.py", line 62, in just_run
    return loop.run_until_complete(coro)
  File "C:\Users\zimme\miniconda3\envs\blm\lib\asyncio\base_events.py", line 646, in run_until_complete
    return future.result()
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\nbclient\client.py", line 663, in async_execute
    await self.async_execute_cell(
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\nbclient\client.py", line 965, in async_execute_cell
    await self._check_raise_for_error(cell, cell_index, exec_reply)
  File "C:\Users\zimme\miniconda3\envs\blm\lib\site-packages\nbclient\client.py", line 862, in _check_raise_for_error
    raise CellExecutionError.from_cell_and_msg(cell, exec_reply_content)
nbclient.exceptions.CellExecutionError: An error occurred while executing the following cell:
------------------
import numpy as np
import matplotlib.pyplot as plt
from mpl_toolkits.axes_grid1 import make_axes_locatable
import scipy.interpolate as interpolate

plt.rc('font', size=15)

# digitized soundspeed
gg=np.array([ 
       [47.0000,  381.0192],
       [47.0000,   20.6859],
      [475.4444,  381.0192],
       [47.0000,   30.3269],
       [50.7991,   81.5449],
       [53.1171,  142.4038],
       [54.0442,  202.6603],
       [56.8258,  262.3141],
       [66.0975,  322.5705],
       [77.2236,  358.1218],
       [90.6676,  373.7885],
      [118.4828,  378.6090],
      [137.4898,  376.1987],
      [168.5501,  364.7500],
      [190.3387,  357.5192],
      [260.3403,  337.0321],
      [332.1962,  317.7500],
      [403.5885,  302.6859],
      [473.5901,  287.0192]]);

# generate sound speed profile
D1=np.interp(gg[3:,0],np.array([gg[3,0],gg[2,0]]),np.array([0,600]));
C1=np.interp(gg[3:,1],np.array([gg[3,1],gg[2,1]]),np.array([1535,1510]));
D1=np.append(D1,1000)
C1=np.append(C1,1521)

#interpolate 
dz=np.arange(1000)
cv=np.array([-dz,interpolate.pchip_interpolate(D1,C1,dz)]).T

th=[-1.0, -3.2, 4.3]; # ray angles
hh=-531.0; # receiver depth

xx=np.arange(10000);
bot=-600-1.5e-2*xx;

pp,tr=ray_tracing(th,hh,xx,bot,cv);

fig = plt.figure("figure.figsize",[15,10])
ax = plt.gca()
divider = make_axes_locatable(ax)
ax2 = divider.append_axes("left", size="20%", pad=1)

ax2.plot(cv[:,1],cv[:,0]);
ax2.plot([1510,1535],[0,0],'k');

ax.plot(xx,pp);
ax.plot(xx,bot,'k',linewidth=3);
ax.plot(xx,0*xx,'k');

ax.set_ylim(min(bot-50),50);
ax2.set_ylim(min(bot-50),50);
------------------

[1;31m---------------------------------------------------------------------------[0m
[1;31mModuleNotFoundError[0m                       Traceback (most recent call last)
Input [1;32mIn [4][0m, in [0;36m<cell line: 4>[1;34m()[0m
[0;32m      2[0m [38;5;28;01mimport[39;00m [38;5;21;01mmatplotlib[39;00m[38;5;21;01m.[39;00m[38;5;21;01mpyplot[39;00m [38;5;28;01mas[39;00m [38;5;21;01mplt[39;00m
[0;32m      3[0m [38;5;28;01mfrom[39;00m [38;5;21;01mmpl_toolkits[39;00m[38;5;21;01m.[39;00m[38;5;21;01maxes_grid1[39;00m [38;5;28;01mimport[39;00m make_axes_locatable
[1;32m----> 4[0m [38;5;28;01mimport[39;00m [38;5;21;01mscipy[39;00m[38;5;21;01m.[39;00m[38;5;21;01minterpolate[39;00m [38;5;28;01mas[39;00m [38;5;21;01minterpolate[39;00m
[0;32m      6[0m plt[38;5;241m.[39mrc([38;5;124m'[39m[38;5;124mfont[39m[38;5;124m'[39m, size[38;5;241m=[39m[38;5;241m15[39m)
[0;32m      8[0m [38;5;66;03m# digitized soundspeed[39;00m

[1;31mModuleNotFoundError[0m: No module named 'scipy'
ModuleNotFoundError: No module named 'scipy'

